// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAYWLsv49fgBW2DxbLkcWCCm0cncXSfal8',
    appId: '1:789723357751:web:4ab92ca17313f30196d5b2',
    messagingSenderId: '789723357751',
    projectId: 'dailify-569ac',
    authDomain: 'dailify-569ac.firebaseapp.com',
    storageBucket: 'dailify-569ac.firebasestorage.app',
    measurementId: 'G-3NF1C0G86F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdS492cBJg6C0f6GU8IFtV0oyUHx3SK3M',
    appId: '1:789723357751:android:e7f17eca2e8cddd096d5b2',
    messagingSenderId: '789723357751',
    projectId: 'dailify-569ac',
    storageBucket: 'dailify-569ac.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBtjzLailX_rh6r2OJ0pq1kg6ap3bi7lgo',
    appId: '1:789723357751:ios:f838a5d70fd2eb7e96d5b2',
    messagingSenderId: '789723357751',
    projectId: 'dailify-569ac',
    storageBucket: 'dailify-569ac.firebasestorage.app',
    iosBundleId: 'com.example.dailify',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBtjzLailX_rh6r2OJ0pq1kg6ap3bi7lgo',
    appId: '1:789723357751:ios:f838a5d70fd2eb7e96d5b2',
    messagingSenderId: '789723357751',
    projectId: 'dailify-569ac',
    storageBucket: 'dailify-569ac.firebasestorage.app',
    iosBundleId: 'com.example.dailify',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAYWLsv49fgBW2DxbLkcWCCm0cncXSfal8',
    appId: '1:789723357751:web:6709dba409b9c46696d5b2',
    messagingSenderId: '789723357751',
    projectId: 'dailify-569ac',
    authDomain: 'dailify-569ac.firebaseapp.com',
    storageBucket: 'dailify-569ac.firebasestorage.app',
    measurementId: 'G-DJC4WLB1GV',
  );

}